FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS build
WORKDIR /app

# copy csproj and restore as distinct layers
COPY *.sln .
COPY apka/*.csproj ./apka/
RUN dotnet restore

# copy everything else and build app
COPY apka/. ./apka/
WORKDIR /apka/apka
RUN dotnet publish -c Release -o out


FROM mcr.microsoft.com/dotnet/core/aspnet:3.0 AS runtime
WORKDIR /apka
COPY --from=build /apka/apka/out ./
ENTRYPOINT ["dotnet", "aspnetapp.dll"]
